stages:
  - test
  - sbom
  - release-images

include:  
  - component: gitlab.com/flarenetwork/infra-public/ci-components/dependency-track@~latest
  - component: gitlab.com/flarenetwork/ci-components-private/lgtm@2
  - component: gitlab.com/flarenetwork/ci-components-private/lint-helm@2
  - component: gitlab.com/flarenetwork/ci-components-private/lint-dockerfile@2
  # CONTAINER IMAGE RELEASE COMPONENT
  - component: gitlab.com/flarenetwork/ci-components-private/release-image@2
    inputs:
      image_name: "fasset-agent-ui"
      image_tag_source: commit_tag
      build_tags: ["flarenetwork-lg"]
      registry_auth: "gitlab"
      push_to_sandbox: false
      staging_registry: "$CI_REGISTRY_IMAGE"
      production_registry: "$CI_REGISTRY_IMAGE"
